---
title: "Raspi"
output: html_document
date: "2024-08-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(plotly)
```

## データの読み込み

```{r}
data_raspi4 <- read_tsv("../raspi4.tsv") %>% mutate(cpu = "A72")
data_raspi4_br <- read_tsv("../raspi4_br.tsv") %>% mutate(cpu = "A72br")
data_raspi5 <- read_tsv("../raspi5.tsv") %>% mutate(cpu = "A76")
data_raspi5_br <- read_tsv("../raspi5.tsv") %>% mutate(cpu = "A76br")
data <- union_all(data_raspi4, data_raspi5) %>% mutate(cpu = cpu %>% as_factor)
```

## Raspberry Pi 4

### 分岐履歴の長さ

```{r}
p <- data_raspi4 %>%
  group_by(inner) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  filter(inner <= 60) %>%
  ggplot(
    mapping = aes(
      x = inner,
      y = log10(branch_misses),
    )
  ) +
  theme_bw() +
  geom_point() +
  geom_line() +
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）") +
  scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  scale_y_continuous(limits = c(5, 11)) +
  geom_vline(xintercept = 32, color = "red", linetype = "dashed")
plot(p)
ggsave("ghr_length_raspi4.png", width = 1920, height = 1080, units = "px")
```

32を境に分岐予測ミスが増加している。
従って、32+1=33回分の分岐履歴を保持している。

### 分岐履歴はどういう表現か？


```{r}
p <- union_all(data_raspi4 %>% mutate(insert = "nop"),
          data_raspi4_br %>% mutate(insert = "untaken br")) %>%
  mutate(insert = as_factor(insert)) %>%
  group_by(inner, insert) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  filter(inner <= 60) %>%
  ggplot(mapping = aes(
    x = inner,
    y = log10(branch_misses),
    color = insert,
    shape = insert,
  )) +
  theme_bw() +
  geom_point() +
  geom_line() +
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）") +
  scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  scale_y_continuous(limits = c(5, 11)) +
  geom_vline(xintercept = 32,
             color = "red",
             linetype = "dashed")
plot(p)
ggsave("ghr_reps_raspi4.png", width = 1920, height = 1080, units = "px")
```

## Raspberry Pi 5

### 分岐履歴の長さ

```{r}
p <- data_raspi5 %>%
  group_by(inner) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  ggplot(
    mapping = aes(
      x = inner,
      y = log10(branch_misses),
    )
  ) +
  theme_bw() +
  geom_point() +
  geom_line() +
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）") +
  # scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  scale_y_continuous(limits = c(5, 10))
plot(p)
ggsave("ghr_length_raspi5.png", width = 1920, height = 1080, units = "px")
p <- data_raspi5 %>%
  group_by(inner) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  filter(between(inner, 350, 400)) %>%
  ggplot(
    mapping = aes(
      x = inner,
      y = log10(branch_misses),
    )
  ) +
  theme_bw() +
  geom_point() +
  geom_line() +
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）") +
  # scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  scale_y_continuous(limits = c(5, 10))
plot(p)
ggsave("ghr_length_raspi5_detail.png", width = 1920, height = 1080, units = "px")
```

### 分岐履歴の表現


```{r}
p <- union_all(data_raspi5 %>% mutate(insert = "nop"),
          data_raspi5_br %>% mutate(insert = "untaken br")) %>%
  mutate(insert = as_factor(insert)) %>%
  group_by(inner, insert) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  # filter(inner <= 60) %>%
  ggplot(mapping = aes(
    x = inner,
    y = log10(branch_misses),
    color = insert,
    shape = insert,
  )) +
  theme_bw() +
  geom_point() +
  geom_line()
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）") +
  # scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  # scale_y_continuous(limits = c(5, 11)) +
  # geom_vline(xintercept = 32,
  #            color = "red",
  #            linetype = "dashed")
plot(p)
ggsave("ghr_reps_raspi5.png", width = 1920, height = 1080, units = "px")
p <- union_all(data_raspi5 %>% mutate(insert = "nop"),
          data_raspi5_br %>% mutate(insert = "untaken br")) %>%
  mutate(insert = as_factor(insert)) %>%
  group_by(inner, insert) %>%
  summarise(branch_misses = sum(branch_misses)) %>%
  filter(between(inner, 350, 400)) %>%
  ggplot(mapping = aes(
    x = inner,
    y = log10(branch_misses),
    color = insert,
    shape = insert,
  )) +
  theme_bw() +
  geom_point() +
  geom_line() +
  labs(x = "内側のループの周回数", y = "log10（分岐予測ミス回数）")
  # scale_x_continuous(limits = c(0, 60), breaks = 0:20 * 5) +
  # scale_y_continuous(limits = c(5, 11)) +
plot(p)
ggsave("ghr_reps_raspi5_detail.png", width = 1920, height = 1080, units = "px")
```

## NOP命令の数と分岐予測ミス回数

### RasPi4

```{r}
for(n2 in 0:8) {
  p <- data_raspi4 %>%
    filter(nop2 == n2 & inner <= 40) %>%
    ggplot(mapping = aes(
      x = inner,
      y = nop,
      colour = log10(branch_misses),
      fill = log10(branch_misses)
    )) +
    theme_bw() +
    geom_tile() +
    labs(
      x = "内側のループの周回数",
      y = "ループの前に挿入されたNOPの数",
      title = sprintf("内側のループの直後に挿入されたNOPの数 %d", n2)
    ) +
    scale_y_continuous(breaks = 0:8) +
    scale_x_continuous(breaks = 0:40 * 5, minor_breaks = 0:40)
  plot(p)
  ggsave(
    sprintf("nop_outer_%d_raspi4.png", n2),
    width = 1920,
    height = 1080,
    units = "px"
  )
}
```

### Raspi5

```{r}
for(n2 in 0:8) {
  p <- data_raspi5 %>%
    filter(nop2 == n2) %>%
    ggplot(mapping = aes(
      x = inner,
      y = nop,
      colour = log10(branch_misses),
      fill = log10(branch_misses)
    )) +
    theme_bw() +
    geom_tile() +
    labs(
      x = "内側のループの周回数",
      y = "ループの前に挿入されたNOPの数",
      title = sprintf("内側のループの直後に挿入されたNOPの数 %d", n2)
    ) +
    scale_y_continuous(breaks = 0:8) +
    scale_x_continuous(breaks = 0:30 * 50, minor_breaks = 0:30 * 10)
  plot(p)
  ggsave(
    sprintf("nop_outer_%d_raspi5.png", n2),
    width = 1920,
    height = 1080,
    units = "px"
  )
}
```


```{r}
# 失敗
# for (outer_br in (0:8 * 4 + 1916)) {
#   p <- data_raspi4 %>%
#     filter(br2 == outer_br & inner <= 40) %>%
#     ggplot(mapping = aes(
#       x = inner,
#       y = br1,
#       colour = log10(branch_misses),
#       fill = log10(branch_misses)
#     )) +
#     theme_bw() +
#     geom_tile() +
#     labs(x = "内側のループの周回数", y = "内側のループの分岐命令のPC", title = sprintf("外側のループの分岐命令のPC：0x%x", outer_br)) +
#     scale_y_continuous(breaks = 1908 + 0:8 * 4) +
#     scale_x_continuous(breaks = 0:40 * 5, minor_breaks = 0:40)
#   plot(p)
# }
```


## お試し

### 3D

```{r}
fig <- plot_ly(
  data_raspi4 %>% filter(inner <= 40),
  x = ~ br1,
  y = ~ br2,
  z = ~ inner,
  color = ~ log10(branch_misses)
) %>% add_markers()
fig
fig <- plot_ly(
  data_raspi5,
  x = ~ br1,
  y = ~ br2,
  z = ~ inner,
  color = ~ log10(branch_misses)
) %>% add_markers()
fig

```

